// Generated by CoffeeScript 1.6.3
(function() {
  var Process, parser, pin, proc, vmHandler;

  proc = require('child_process');

  pin = require('./pin');

  parser = require('./parser');

  vmHandler = require('../vmHandler');

  class Process {
    constructor() {
      this.process = void 0;
      this.bin = 'qemu-system-x86_64';
    }

    start(vmConf) {
      var args, e;
      try {
        args = parser.vmCfgToArgs(vmConf);
        this.process = proc.spawn(this.bin, args.args, {
          stdio: 'inherit',
          detached: true
        });
        console.log("QEMU-Process: Start-Parameters: " + (args.args.join(' ')));
        console.log("pinnig QEMU-Process");
        pin(this.process.pid, vmConf.hardware.cpus, vmConf.hardware.cpuPin);
        return this.process.on('exit', function(code, signal) {
          if (code === 0) {
            console.log("QEMU-Process: exit clean.");
          } else {
            console.error("QEMU-Process: exit with error: " + code + ", signal: " + signal);
          }
          vmHandler.SHUTDOWN(vmConf.name);
          return vmHandler.stopQMP(vmConf.name);
        });
      } catch (_error) {
        e = _error;
        console.error("process:start:e");
        console.dir(e);
        vmHandler.SHUTDOWN(vmConf.name);
        return vmHandler.stopQMP(vmConf.name);
      }
    }
  }

  module.exports.Process = Process;

}).call(this);
