// Generated by CoffeeScript 1.6.3
(function() {
  var os, sys;

  os = require('os');

  sys = {'totalmem': os.totalmem(), 'cores': os.cpus().length / 2};

  module.exports.settings = sys;

}).call(this);
