// Generated by CoffeeScript 1.6.3
(function() {
  let fs, open, remove, save;

  fs = require('fs');

  save = function(vmCfg) {
    var e;
    try {
      fs.writeFileSync(`vmConfigs/${vmCfg.name}.json`, JSON.stringify(vmCfg));
    } catch (_error) {
      e = _error;
      console.error("save error");
      console.dir(e);
      return false;
    }
    return true;
  };

  open = function(vmName, cb) {
    var cfg, e;
    try {
      cfg = fs.readFileSync(`vmConfigs/${vmName}.json`);
      return cb({
        status: 'success',
        data: JSON.parse(cfg)
      });
    } catch (_error) {
      e = _error;
      console.dir(e);
      return cb({
        status: 'error',
        data: void 0
      });
    }
  };

  remove = function(vmName) {
    var e;
    try {
      fs.unlinkSync(`vmConfigs/${vmName}.json`);
    } catch (_error) {
      e = _error;
      console.error(`remove ${vmName} error`);
      return false;
    }
    return true;
  };

  exports.save = save;

  exports.open = open;

  exports.remove = remove;

}).call(this);
